<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Description>Simple and easy to use Among Us modding API.</Description>
        <PackageId>AllOfUs.MiraAPI</PackageId>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Nullable>disable</Nullable>
        <WarningsAsErrors>$(WarningsAsErrors);CS8632</WarningsAsErrors>

        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch>true</ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <DisableUnmanagedBindingResolution>true</DisableUnmanagedBindingResolution>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*" />
    </ItemGroup>

    <Import Project="../AmongUs.props" />
</Project>
